####################################################################################
#  docker-compose file for syn-guac app - Apache Guacamole on Synology DiskStation
####################################################################################
# The initial login to the guacamole webinterface is:
#
#     Username: guacadmin
#     Password: guacadmin
#
# Make sure you change it immediately!
####################################################################################
version: '3.0'
networks:
  internal_network:
    driver: bridge
    # driver: macvlan
    # driver_opts:
    #   parent: eth0
    # ipam:
    #   config:
    #     - subnet: ${SUBNET}
    #       gateway: ${GATEWAY}
volumes:
  letsencrypt:
services:
  guacd:
    container_name: guac_guacd
    image: guacamole/guacd
    networks:
      internal_network:
    restart: always
    volumes:
      - ./guacamole/drive:/drive:rw
      - ./guacamole/record:/record:rw
  postgres:
    container_name: guac_postgres
    image: postgres
    restart: always
    networks:
      internal_network:
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d:ro
      - ./database/data:/var/lib/postgresql/data:rw
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  guacamole:
    container_name: guac_guacamole
    image: guacamole/guacamole
    restart: always
    depends_on:
      - guacd
      - postgres
    networks:
      internal_network:
    ports:
      - 8080/tcp
    links:
      - guacd
    volumes:
#      - ./guacamole/conf/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./cert-import:/cert-import:ro
      - ./scripts/certimport-entrypoint.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      LDAP_HOSTNAME: ${LDAP_HOSTNAME}
      LDAP_PORT: 636
      LDAP_ENCRYPTION_METHOD: ssl
      LDAP_SEARCH_BIND_DN: ${LDAP_SEARCH_BIND_DN}
      LDAP_SEARCH_BIND_PASSWORD: ${LDAP_SEARCH_BIND_PASSWORD}
      LDAP_USER_BASE_DN: ${LDAP_USER_BASE_DN}
      LDAP_USERNAME_ATTRIBUTE: sAMAccountName
      LDAP_USER_SEARCH_FILTER: ${LDAP_USER_SEARCH_FILTER}
      LDAP_GROUP_BASE_DN: ${LDAP_GROUP_BASE_DN}
  nginx:
    container_name: guac_nginx-certbot
    image: staticfloat/nginx-certbot
    restart: always
    networks:
      internal_network:
#        ipv4_address: ${LISTEN_IP}
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
    links:
      - guacamole
    volumes:
      #- ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/certbot.conf:/etc/nginx/conf.d/certbot.conf:ro
      - ./nginx/conf/default.conf:/etc/nginx/user.conf.d/default.conf:ro
      - ./nginx/wwwroot:/etc/nginx/static:ro
      - letsencrypt:/etc/letsencrypt:rw
      #- ./nginx/access.log:/var/log/nginx/access.log:rw
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      FQDN: ${CERTBOT_FQDN}
      ENVSUBST_VARS: FQDN
