####################################################################################
#  docker-compose file for syn-guac - Apache Guacamole on Synology DiskStation
####################################################################################
# The initial login to the guacamole webinterface is:
#
#     Username: guacadmin
#     Password: guacadmin
#
# Make sure you change it immediately!
####################################################################################
version: '3.0'
networks:
  internal_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/24
   
volumes:
  letsencrypt:
services:
  guacd:
    container_name: syn-guac_guacd
    image: guacamole/guacd
    networks:
      internal_network:
    restart: always
    volumes:
      - ./guacamole/drive:/drive:rw
      - ./guacamole/record:/record:rw
  postgres:
    container_name: syn-guac_postgres
    image: postgres
    restart: always
    networks:
      internal_network:
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d:ro
      - ./database/data:/var/lib/postgresql/data:rw
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  guacamole:
    container_name: syn-guac_guacamole
    image: guacamole/guacamole
    restart: always
    depends_on:
      - guacd
      - postgres
    networks:
      internal_network:
    ports:
      - 8080/tcp
    links:
      - guacd
    volumes:
      - ./guacamole/conf/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./guacamole/entrypoint/certimport-entrypoint.sh:/tmp/entrypoint.sh:ro
      - ./cert-import:/tmp/cert-import:ro
    entrypoint: /tmp/entrypoint.sh
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      LDAP_HOSTNAME: "${DISKSTATION_NAME}.${ORG_DOMAIN_NAME}.${ORG_DOMAIN_SUFFIX}"
      LDAP_PORT: 636
      LDAP_ENCRYPTION_METHOD: ssl
      LDAP_SEARCH_BIND_DN: "CN=ldap_user,CN=Users,DC=${ORG_DOMAIN_NAME},DC=${ORG_DOMAIN_SUFFIX}"
      LDAP_SEARCH_BIND_PASSWORD: ${LDAP_SEARCH_BIND_PASSWORD}
      LDAP_USER_BASE_DN: "OU=Users,OU=MyOrg,DC=${ORG_DOMAIN_NAME},DC=${ORG_DOMAIN_SUFFIX}"
      LDAP_USERNAME_ATTRIBUTE: sAMAccountName
      LDAP_USER_SEARCH_FILTER: "(&(objectCategory=user)(objectClass=user)(memberOf=CN=Guacamole Users,OU=Groups,OU=MyOrg,DC=${ORG_DOMAIN_NAME},DC=${ORG_DOMAIN_SUFFIX}))"
      LDAP_GROUP_BASE_DN: "OU=Groups,OU=MyOrg,DC=${ORG_DOMAIN_NAME},DC=${ORG_DOMAIN_SUFFIX}"
  nginx:
    container_name: syn-guac_nginx-certbot
    image: staticfloat/nginx-certbot
    restart: always
    networks:
     internal_network:
        ipv4_address: 172.31.0.254
    ports:
      - 8080:80/tcp
      - 8443:443/tcp
    links:
      - guacamole
    volumes:
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - ./nginx/static:/etc/nginx/static:ro
      - letsencrypt:/etc/letsencrypt:rw
      environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      FQDN: ${CERTBOT_FQDN}
      ENVSUBST_VARS: FQDN
      