####################################################################################
# docker-compose file for Apache Guacamole on Synology DiskStation
####################################################################################
#
# !!!!! FOR INITAL SETUP (after git clone) run ./prepare.sh once
#
# !!!!! FOR A FULL RESET (WILL ERASE YOUR DATABASE, YOUR FILES, YOUR RECORDS AND CERTS) DO A
# !!!!!  ./reset.sh
#
#
# The initial login to the guacamole webinterface is:
#
#     Username: guacadmin
#     Password: guacadmin
#
# Make sure you change it immediately!
####################################################################################

version: '3.0'

# networks
# create a network 'guac_network' in mode 'bridged'
networks:
  internal_network:
    driver: bridge

volumes:
  letsencrypt:

# services
services:
  guacd:
    container_name: syn-guac_guacd
    image: guacamole/guacd
    networks:
      internal_network:
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
  postgres:
    container_name: syn-guac_postgres
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    image: postgres
    networks:
      internal_network:
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:ro
    - ./data:/var/lib/postgresql/data:rw
  guacamole:
    container_name: syn-guac_guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      LDAP_HOSTNAME: "${DISKSTATION_NAME}.${ORG_DOMAIN_NAME}.${ORG_DOMAIN_SUFFIX}"
      LDAP_PORT: 636
      LDAP_ENCRYPTION_METHOD: ssl
      LDAP_SEARCH_BIND_DN: "CN=ldap_user,CN=Users,DC=${ORG_DOMAIN_NAME},DC=${ORG_DOMAIN_SUFFIX}"
      LDAP_SEARCH_BIND_PASSWORD: ${LDAP_SEARCH_BIND_PASSWORD}
      LDAP_USER_BASE_DN: "OU=Users,OU=MyOrg,DC=${ORG_DOMAIN_NAME},DC=${ORG_DOMAIN_SUFFIX}"
      LDAP_USERNAME_ATTRIBUTE: sAMAccountName
      LDAP_USER_SEARCH_FILTER: "(&(objectCategory=user)(objectClass=user)(memberOf=CN=Guacamole Users,OU=Groups,OU=MyOrg,DC=${ORG_DOMAIN_NAME},DC=${ORG_DOMAIN_SUFFIX}))"
      LDAP_GROUP_BASE_DN: "OU=Groups,OU=MyOrg,DC=${ORG_DOMAIN_NAME},DC=${ORG_DOMAIN_SUFFIX}"
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      internal_network:
    ports:
    - 8080/tcp
    restart: always
    volumes:
    - ./cert-import:/tmp/cert-import:ro
    entrypoint: /tmp/cert-import/install-cert-startup.sh
  nginx:
   container_name: syn-guac_nginx-certbot
   restart: always
   image: staticfloat/nginx-certbot
   volumes:
   - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
   - ./nginx/static:/etc/nginx/static:ro
   - letsencrypt:/etc/letsencrypt:rw
   ports:
   - 8080:80/tcp
   - 8443:443/tcp
   links:
   - guacamole
   networks:
     internal_network:
   environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      FQDN: ${CERTBOT_FQDN}
      ENVSUBST_VARS: FQDN
