####################################################################################
#  docker-compose file for syn-guac proxy - Apache Guacamole on Synology DiskStation
####################################################################################
version: '3.0'
networks:
  internal_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/24
  nginx:
    container_name: syn-guac_nginx-certbot
    image: staticfloat/nginx-certbot
    restart: always
    networks:
     internal_network:
        ipv4_address: 172.31.0.254
    ports:
      - 8080:80/tcp
      - 8443:443/tcp
    links:
      - guacamole
    volumes:
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - ./nginx/static:/etc/nginx/static:ro
      - letsencrypt:/etc/letsencrypt:rw
      environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      FQDN: ${CERTBOT_FQDN}
      ENVSUBST_VARS: FQDN
      