####################################################################################
# docker-compose file for syn-guac proxy - Apache Guacamole on Synology DiskStation
####################################################################################
version: '3.0'
volumes:
  letsencrypt:
services:
  nginx:
    container_name: syn-guac_nginx-certbot
    image: staticfloat/nginx-certbot
    restart: always
    network-mode: host
    ports:
      - 80/tcp
      - 443/tcp
    links:
      - guacamole
    volumes:
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - ./nginx/static:/etc/nginx/static:ro
      - letsencrypt:/etc/letsencrypt:rw
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      FQDN: ${CERTBOT_FQDN}
      ENVSUBST_VARS: FQDN
