####################################################################################
# docker-compose file for syn-guac proxy - Apache Guacamole on Synology DiskStation
####################################################################################
version: '2.0'
networks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
volumes:
  letsencrypt:
services:
  nginx:
    container_name: guac_nginx-certbot
    image: staticfloat/nginx-certbot
    restart: always
    networks:
      macvlan_network:
        ipv4_address: 10.0.0.11
    ports:
      - 10.0.0.11:8080:8080/tcp
      - 10.0.0.11:8443:8443/tcp
#    links:
#      - guacamole
    volumes:
      #- ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/certbot.conf:/etc/nginx/conf.d/certbot.conf:ro
      - ./nginx/conf/default.conf:/etc/nginx/user.conf.d/default.conf:ro
      - ./nginx/wwwroot:/etc/nginx/static:ro
      - letsencrypt:/etc/letsencrypt:rw
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      FQDN: ${CERTBOT_FQDN}
      ENVSUBST_VARS: FQDN
