# syn-guac.conf
# This file contains implementation specific settings and should be adjusted prior to being run.

# The email address submitted to Lets Encrypt when obtaining a certificate.
CERTBOT_EMAIL="support@example.co.uk"

# The external FQDN (subject name) submitted to Lets Encrypt when obtaining a certificate.
# For this to work, external DNS needs to be set up to point to the network's router's public IP
# which is, in turn, port forwarding 80/tcp and 443/tcp to the DiskStation.
CERTBOT_FQDN="remote.example.co.uk"

# Server and Samba AD Domain details.
DISKSTATION_NAME=diskstation
ORG_DOMAIN_NAME=example
ORG_DOMAIN_SUFFIX=local

# Database password.
DB_PASSWORD="ChooseYourOwnPasswordHere1234"

# LDAP Bind DN password for ldap_user account.
LDAP_SEARCH_BIND_PASSWORD="ChooseAnotherPasswordHere5678"
